CREATE TABLE TB_USER(
	USER_NO     NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
	USER_ID     VARCHAR2(30) NOT NULL,
	USER_PW     VARCHAR2(30) NOT NULL,
	USER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_USER.USER_NO     IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID     IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME   IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';


-- USER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT * FROM TB_USER;

DELETE FROM tb_user WHERE UER_ID = 'user';

COMMIT;




CREATE TABLE TB_AREA(
	AREA_CODE     VARCHAR2(10),
	AREA_NAME     VARCHAR2(30) NOT NULL
);
INSERT INTO TB_AREA 
VALUES('02','서울');
INSERT INTO TB_AREA 
VALUES('031', '경기' );
INSERT INTO TB_AREA 
VALUES('032', '인천');

SELECT * FROM TB_AREA;


CREATE TABLE TB_MEMBER(
	MEMBER_ID     VARCHAR2(30) NOT NULL,
	MEMBER_PW     VARCHAR2(30) NOT NULL,
	MEMBER_NAME   VARCHAR2(30) NOT NULL,
	GRADE		NUMBER,
	AREA_CODE			VARCHAR2(10)
);

INSERT INTO TB_MEMBER 
VALUES('hong01', 'pass01', '홍길동', 10, '02');
INSERT INTO TB_MEMBER 
VALUES('ss5000', 'pass02', '이순신', 10, '032');
INSERT INTO TB_MEMBER 
VALUES('pcc1234', 'pass05', '박철수', 20, '031' );
INSERT INTO TB_MEMBER 
VALUES('aa1234', 'pass06', '김뫄뫄', 30, '032' );



SELECT MEMBER_ID AS 아이디, MEMBER_PW 비밀번호, MEMBER_NAME AS 이름, GRADE_MANE AS 등급명,
AREA_NAME 지역명
FROM TB_MEMBER
JOIN USER_GRADE ON (GRADE = GRADE_CODE)
JOIN TB_AREA USING(AREA_CODE)
WHERE (GRADE, AREA_CODE) IN 
    (SELECT GRADE, AREA_CODE FROM TB_MEMBER
    WHERE MEMBER_ID LIKE '%123%')
ORDER BY MEMBER_ID DESC;

SELECT * FROM TB_MEMBER;